/**
 * Enqueue a single translation task to Cloud Tasks (translation-es queue).
 * Uses OIDC so the worker can restrict invoker to the Tasks service account.
 * Task name is auto-generated by Cloud Tasks; we only count as enqueued when createTask returns a created task name.
 */

import { execSync } from 'child_process';
import { CloudTasksClient } from '@google-cloud/tasks';
import type { TranslationTaskPayload } from '../translation';

const tasks = new CloudTasksClient();

const PROJECT_ID = process.env.GCLOUD_PROJECT || process.env.GCP_PROJECT;
const LOCATION = process.env.TASKS_LOCATION || 'us-central1';
const QUEUE = process.env.TASKS_QUEUE_TRANSLATION || 'translation-es';
const TASKS_SA_EMAIL = process.env.TASKS_SERVICE_ACCOUNT_EMAIL;

const TRANSLATION_WORKER_SERVICE = process.env.TRANSLATION_WORKER_SERVICE ?? 'processtranslationjob';

function getWorkerUrl(): string {
  const fromEnv = process.env.TRANSLATION_WORKER_URL;
  if (fromEnv?.trim()) return fromEnv.trim();

  try {
    const url = execSync(
      `gcloud run services describe ${TRANSLATION_WORKER_SERVICE} --region ${LOCATION} --format='value(status.url)'`,
      { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }
    )
      .trim();
    if (url) return url;
  } catch {
    // fall through to error
  }

  throw new Error(
    'Missing TRANSLATION_WORKER_URL. Get it with: gcloud run services describe processtranslationjob --region us-central1 --format=\'value(status.url)\''
  );
}

export interface EnqueueTranslationTaskOptions {
  /** If > 0, task is scheduled for now + this many seconds (so it appears in gcloud tasks list for debugging). */
  scheduleDelaySeconds?: number;
}

/** Resolved enqueue config for logging (project, location, queue, workerUrl, serviceAccountEmail). */
export function getEnqueueConfig(): {
  project: string;
  location: string;
  queue: string;
  workerUrl: string;
  serviceAccountEmail: string;
} {
  if (!PROJECT_ID) throw new Error('Missing GCLOUD_PROJECT / GCP_PROJECT');
  const workerUrl = getWorkerUrl();
  if (!TASKS_SA_EMAIL) throw new Error('Missing TASKS_SERVICE_ACCOUNT_EMAIL');
  return {
    project: PROJECT_ID,
    location: LOCATION,
    queue: QUEUE,
    workerUrl,
    serviceAccountEmail: TASKS_SA_EMAIL,
  };
}

/** Returns the created (or existing) task name on success; throws on failure. */
export async function enqueueTranslationTask(
  payload: TranslationTaskPayload,
  options?: EnqueueTranslationTaskOptions
): Promise<string> {
  if (!PROJECT_ID) throw new Error('Missing GCLOUD_PROJECT / GCP_PROJECT');
  const workerUrl = getWorkerUrl();
  if (!TASKS_SA_EMAIL) throw new Error('Missing TASKS_SERVICE_ACCOUNT_EMAIL');

  const parent = tasks.queuePath(PROJECT_ID, LOCATION, QUEUE);

  const task: { httpRequest: object; scheduleTime?: { seconds: number; nanos?: number } } = {
    httpRequest: {
      httpMethod: 'POST' as const,
      url: workerUrl,
      headers: { 'Content-Type': 'application/json' },
      body: Buffer.from(JSON.stringify(payload), 'utf8').toString('base64'),
      oidcToken: {
        serviceAccountEmail: TASKS_SA_EMAIL,
      },
    },
  };

  const delaySec = options?.scheduleDelaySeconds ?? 0;
  if (delaySec > 0) {
    task.scheduleTime = {
      seconds: Math.floor(Date.now() / 1000) + delaySec,
      nanos: 0,
    };
  }

  const config = { project: PROJECT_ID, location: LOCATION, queue: QUEUE, workerUrl, serviceAccountEmail: TASKS_SA_EMAIL };

  try {
    const [created] = await tasks.createTask({ parent, task });
    return created.name ?? '';
  } catch (e: unknown) {
    const code = (e as { code?: number })?.code;
    const message = (e as { message?: string })?.message;
    console.error('[TASKS] createTask failed', { code, message, ...config });
    throw e;
  }
}
