/**
 * Facility / venue type options for CRM company locations (Add/Edit location forms).
 */
export const LOCATION_FACILITY_TYPE_OPTIONS: readonly string[] = [
  'Office',
  'Warehouse',
  'Plant',
  'Distribution Center',
  'Manufacturing',
  'Retail',
  'Branch',
  'Headquarters',
  'Data Center',
  'Call Center',
  'Research & Development',
  'Training Center',
  'Service Center',
  'Showroom',
  'Storage Facility',
  'Hotel',
  'Medical Clinic',
  'Hospital',
  'Retirement Home',
  'Sports Arena',
  'Sports Stadium',
  'Golf Course',
  'Race Track',
  'Fairgrounds',
  'Concert Venue',
  'Convention Center',
  'College',
  'High School',
  'Dining Hall',
  'Other',
];
