#!/usr/bin/env node
/**
 * Copies param keys from repo root .env into functions/.env so Firebase deploy
 * doesn't prompt. Run before build (predeploy). Single source of truth: root .env.
 */
const fs = require('fs');
const path = require('path');

const FUNCTIONS_DIR = path.resolve(__dirname, '..');
const ROOT_ENV = path.join(FUNCTIONS_DIR, '..', '.env');
const FIREBASE_JSON = path.join(FUNCTIONS_DIR, '..', 'firebase.json');
const OUT_ENV = path.join(FUNCTIONS_DIR, '.env');

// All defineString / defineSecret keys used in functions (so deploy can read from .env and not prompt)
const PARAM_KEYS = [
  // defineString (params)
  'OPENAI_API_KEY',
  'SERP_API_KEY',
  'GNEWS_API_KEY',
  'GOOGLE_CLIENT_ID',
  'GOOGLE_CLIENT_SECRET',
  'GOOGLE_REDIRECT_URI',
  'SMS_PROVIDER',
  // defineSecret (secrets) – set in root .env if you use these
  'SENDGRID_API_KEY',
  'SENDGRID_FROM_EMAIL',
  'SENDGRID_FROM_NAME',
  'SLACK_SIGNING_SECRET',
  'SLACK_BOT_TOKEN',
  'APOLLO_API_KEY',
  'TWILIO_ACCOUNT_SID',
  'TWILIO_AUTH_TOKEN',
  'TWILIO_MESSAGING_PHONE_NUMBER',
  'TWILIO_A2P_CAMPAIGN',
  'TWILIO_VERIFY_SERVICE_SID',
  'EVERIFY_WS_USERNAME',
  'EVERIFY_WS_PASSWORD',
  'EVERIFY_CLIENT_ID',
  'EVERIFY_CLIENT_SECRET',
];

function parseEnv(content) {
  const out = {};
  for (const line of (content || '').split('\n')) {
    // Support: KEY=value, export KEY=value, and REACT_APP_KEY=value
    const m = line.match(/^\s*(?:export\s+)?([A-Za-z0-9_]+)\s*=\s*(.*)$/);
    if (m) out[m[1].trim()] = m[2].replace(/^["']|["']$/g, '').trim();
  }
  return out;
}

function getValue(rootVars, paramKey) {
  if (rootVars[paramKey] != null && rootVars[paramKey] !== '') return rootVars[paramKey];
  const reactKey = 'REACT_APP_' + paramKey;
  if (rootVars[reactKey] != null && rootVars[reactKey] !== '') return rootVars[reactKey];
  return null;
}

// Build merged vars: root .env (and REACT_APP_* fallbacks) first, then firebase.json environmentVariables as fallback
const rootVars = fs.existsSync(ROOT_ENV)
  ? parseEnv(fs.readFileSync(ROOT_ENV, 'utf8'))
  : {};
let envVars = {};
for (const key of PARAM_KEYS) {
  const v = getValue(rootVars, key);
  if (v != null && v !== '') envVars[key] = v;
}
// Fallback: firebase.json functions[].environmentVariables (e.g. GNEWS_API_KEY, SERP_API_KEY, SMS_PROVIDER)
if (fs.existsSync(FIREBASE_JSON)) {
  try {
    const fb = JSON.parse(fs.readFileSync(FIREBASE_JSON, 'utf8'));
    const fns = Array.isArray(fb.functions) ? fb.functions[0] : fb.functions;
    const fbEnv = fns && fns.environmentVariables;
    if (fbEnv && typeof fbEnv === 'object') {
      for (const key of PARAM_KEYS) {
        if (!envVars[key] && fbEnv[key]) envVars[key] = fbEnv[key];
      }
    }
  } catch (_) {}
}

// Fallback: preserve existing functions/.env so we never wipe keys you set once (e.g. from a past deploy prompt)
if (fs.existsSync(OUT_ENV)) {
  const existing = parseEnv(fs.readFileSync(OUT_ENV, 'utf8'));
  for (const key of PARAM_KEYS) {
    if (!envVars[key] && existing[key]) envVars[key] = existing[key];
  }
}

const lines = [
  '# Auto-generated by scripts/copyEnvFromRoot.js (predeploy): root .env + REACT_APP_* + firebase.json env',
  '',
];
let copied = Object.keys(envVars).length;
for (const key of PARAM_KEYS) {
  const value = envVars[key];
  if (value != null && value !== '') lines.push(`${key}=${value}`);
}
if (copied === 0) {
  console.warn('[copy-env] No params found in root .env (or REACT_APP_*), or firebase.json environmentVariables. Add keys to root .env to avoid deploy prompts.');
}
fs.writeFileSync(OUT_ENV, lines.join('\n') + '\n', 'utf8');
console.log('[copy-env] Wrote', copied, 'params to functions/.env');
