// User Profile Schema for HRX Platform
// Supports both traditional enterprise employees and flexible/gig workforce users

export interface EmergencyContact {
  name: string;
  relationship: string;
  phone: string;
}

export interface ExternalIds {
  workdayId?: string;
  adpId?: string;
  bambooId?: string;
  [key: string]: string | undefined;
}

export interface TraitsProfile {
  // Auto-generated by HRX Traits Engine
  [key: string]: any;
}

export interface CareerPathSuggestion {
  title: string;
  confidence: number;
  reasoning: string;
  requirements: string[];
}

export interface NotificationSettings {
  emailNotifications: boolean;
  pushNotifications: boolean;
  smsNotifications: boolean;
  scheduleUpdates: boolean;
  assignmentUpdates: boolean;
  systemUpdates: boolean;
  marketingEmails: boolean;
  companionNotifications: boolean;
  performanceFeedback: boolean;
  trainingOpportunities: boolean;
  emergencyAlerts: boolean;
}

export interface PrivacySettings {
  profileVisibility: 'public' | 'private' | 'team';
  showContactInfo: boolean;
  showSchedule: boolean;
  allowDataAnalytics: boolean;
  allowLocationSharing: boolean;
}

export interface LocationSettings {
  locationSharingEnabled: boolean;
  locationGranularity: 'always' | 'work_hours' | 'assignments_only' | 'manual' | 'disabled';
  lastLocationUpdate?: Date;
  locationAccuracy: 'high' | 'medium' | 'low';
  geofencingEnabled: boolean;
  backgroundLocationEnabled: boolean;
  batteryOptimizationEnabled: boolean;
  dataUsageOptimized: boolean;
}

export interface UserProfile {
  // 🧍 Basic Identity
  firstName: string;
  lastName: string;
  preferredName?: string;
  email: string;
  phone: string;
  phoneE164?: string; // E.164 formatted phone number
  phoneVerified?: boolean; // Phone verification status
  phoneVerifiedAt?: Date; // When phone was verified
  dob?: string; // Date of birth for eligibility verification
  dateOfBirth?: Date;
  /** Last four digits of SSN (optional; payroll / identity hints). */
  last4SSN?: string;
  preferredLanguage?: 'en' | 'es'; // Preferred language for templated messaging
  gender?: 'Male' | 'Female' | 'Nonbinary' | 'Other' | 'Prefer not to say';
  avatar?: string; // file URL

  // 📍 Employment Classification
  securityLevel: '0' | '1' | '2' | '3' | '4' | '5'; // 0=Dismissed, 1=Applicant, 2=Flex, 3=Worker, 4=Manager, 5=Admin
  employmentType: 'Full-Time' | 'Part-Time' | 'Contract' | 'Flex';
  departmentId: string; // ref ID to Departments collection
  divisionId?: string; // ref ID to Divisions collection
  locationId?: string; // ref ID to Locations collection
  regionId?: string; // ref ID to Regions collection
  managerId?: string; // ref ID to another user

  // 🗂️ Metadata & Structure
  startDate?: Date;
  workStatus: 'Active' | 'On Leave' | 'Terminated' | 'Suspended' | 'Pending';
  workerId?: string; // Optional custom ID from HRIS
  union?: string; // Union name or boolean flag
  /** Legacy/derived: true if authorized to work (from workEligibilityAttestation or legacy boolean). */
  workEligibility?: boolean;
  /** Work eligibility attestation (source of truth); workEligibility is derived for compatibility. */
  workEligibilityAttestation?: import('./workEligibility').WorkEligibilityAttestation;
  languages?: string[]; // Spoken/written languages

  // 🧠 Behavioral AI (HRX-Specific) - Auto-generated
  traitsProfile?: TraitsProfile;
  jobSatisfactionIndex?: number; // Rolling score (1–100)
  burnoutRiskScore?: number; // Rolling score (1–100)
  companionLastActiveAt?: Date; // Last Companion activity timestamp
  careerPathSuggestions?: CareerPathSuggestion[]; // AI-generated career suggestions

  /**
   * Denormalized score summary for fast rendering (per spec).
   * Stored on the user doc and updated by interview/review writes.
   */
  scoreSummary?: {
    aiScore?: number; // 0..100
    aiScoreUpdatedAt?: any;

    interviewAvg?: number; // 0..10 (1 decimal)
    interviewCount?: number;
    interviewLastAt?: any;
    interviewLastScore10?: number; // 0..10 (most recent interview score)

    reviewAvg?: number; // 1..5 (1 decimal)
    reviewCount?: number;
    reviewLastAt?: any;

    responsivenessScore?: number; // 0..100
    completenessScore?: number; // 0..100
    qualityScore?: number; // 0..100

    aiWeights?: {
      completeness: number;
      responsiveness: number;
      quality: number;
    };
  };

  // 🔐 System & Sync
  createdBy: string; // ref ID to admin user who created this worker
  source: 'Manual' | 'Import' | 'Job App' | 'Flex Sign-Up';
  createdAt: Date;
  updatedAt: Date;
  externalIds?: ExternalIds;

  // 🧪 Enrichments
  emergencyContact?: EmergencyContact;
  transportMethod?: 'Car' | 'Public Transit' | 'Bike' | 'Walk' | 'Other';
  /** Admin: worker was added to Indeed Flex (shows badge in profile header when true). */
  addedToIndeedFlex?: boolean;

  // 🔒 Privacy & Notifications
  notificationSettings?: NotificationSettings;
  privacySettings?: PrivacySettings;
  locationSettings?: LocationSettings;

  // Legacy fields for backward compatibility
  role?: string;
  jobTitle?: string;
  department?: string;
  tenantId?: string;
  activeTenantId?: string;
  tenantIds?: string[] | { [tenantId: string]: any };
  userGroupIds?: string[];
  /** Smart Groups: geographic and industry dimensions from application events (separate from User Groups) */
  smartGroupData?: import('../services/smartGroupService').SmartGroupData;
  addressInfo?: any;
  certifications?: any[];
  skills?: any[];
  yearsExperience?: string;
  educationLevel?: string;
  backgroundCheckStatus?: string;
  vaccinationStatus?: string;
  specialTraining?: string;
  // Module access flags (per-user overrides)
  crm_sales?: boolean;
  recruiter?: boolean;
  jobsBoard?: boolean;
  // Resume object - single resume per user
  resume?: {
    fileName: string; // Original filename (e.g., "GregResume.pdf")
    size: number; // File size in bytes (e.g., 106 * 1024 = 108544)
    sizeKB?: number; // File size in KB for display (e.g., 106)
    timestamp: Date; // Upload date
    storagePath: string; // Firebase Storage path
    downloadUrl?: string; // Generated download URL (optional, can be generated client-side)
  };
}

// Form interface for editing user profiles
export interface UserProfileForm {
  // Basic Identity
  firstName: string;
  lastName: string;
  preferredName?: string;
  email: string;
  phone: string;
  linkedinUrl?: string;
  dateOfBirth?: string; // ISO date string for form input
  last4SSN?: string;
  gender?: 'Male' | 'Female' | 'Nonbinary' | 'Other' | 'Prefer not to say';
  
  // Employment Classification
  securityLevel: '0' | '1' | '2' | '3' | '4' | '5'; // 0=Dismissed, 1=Applicant, 2=Flex, 3=Worker, 4=Manager, 5=Admin
  employmentType: 'Full-Time' | 'Part-Time' | 'Contract' | 'Flex';
  departmentId: string;
  divisionId?: string;
  locationId?: string;
  regionId?: string;
  managerId?: string;
  
  // Metadata & Structure
  startDate?: string; // ISO date string for form input
  workStatus: 'Active' | 'On Leave' | 'Terminated' | 'Suspended' | 'Pending';
  workerId?: string;
  union?: string;
  workEligibility?: boolean;
  languages?: string[];
  
  // Enrichments
  emergencyContact?: EmergencyContact;
  transportMethod?: 'Car' | 'Public Transit' | 'Bike' | 'Walk' | 'Other';
  addedToIndeedFlex?: boolean;

  // Legacy fields
  role?: string;
  jobTitle?: string;
  department?: string;
  // Module access flags (per-user overrides)
  crm_sales?: boolean;
  recruiter?: boolean;
  jobsBoard?: boolean;
}

// Validation schema for form validation
export const USER_PROFILE_VALIDATION = {
  firstName: { required: true, minLength: 1, maxLength: 50 },
  lastName: { required: true, minLength: 1, maxLength: 50 },
  email: { required: true, pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/ },
  phone: { required: true, pattern: /^\+?[\d\s()+-]+$/ },
  securityLevel: { required: true },
  employmentType: { required: true },
  departmentId: { required: true },
  workStatus: { required: true },
} as const; 